export type SourceAccess = "live" | "public" | "registration" | "configured";
export type SourcePriority = "high" | "medium" | "watch";

export interface SourceCatalogItem {
  name: string;
  category: string;
  access: SourceAccess;
  priority: SourcePriority;
  signals: string[];
  url: string;
  description: string;
}

export const sourceCatalog: SourceCatalogItem[] = [
  {
    name: "منصة مقاول — المشاريع",
    category: "مشاريع وفرص مقاولات",
    access: "live",
    priority: "high",
    signals: ["مشاريع", "فرص تنفيذ", "موقع", "نشاط", "موعد تسليم"],
    url: "https://muqawil.org/ar/market/list",
    description: "مشاريع وفرص عمل منشورة للعامة مع تاريخ النشر والموقع والنشاط وموعد التسليم وعدد العروض الظاهر. متصل حيًا بالرادار.",
  },
  {
    name: "منصة مقاول — دليل المقاولين",
    category: "شركات ومقاولون",
    access: "live",
    priority: "high",
    signals: ["مقاولون", "عضوية", "حجم منشأة", "منطقة", "تصنيف"],
    url: "https://muqawil.org/ar/contractors",
    description: "دليل عام للمقاولين المسجلين مع العضوية والحجم والموقع والتصنيف وبيانات الجاهزية الظاهرة. متصل حيًا بالرادار.",
  },
  {
    name: "اعتماد — البيانات المفتوحة",
    category: "منافسات وترسيات حكومية",
    access: "configured",
    priority: "high",
    signals: ["منافسات حكومية", "ترسيات", "جهات حكومية", "قيم عقود"],
    url: "https://portal.etimad.sa/ar-SA/ecollaboration/IndexOpenDataRequest",
    description: "المصدر الرسمي لبيانات المنافسات المفتوحة. موصل API موجود، ويُفعّل عند توفر BASE_URL وgroupId الرسميين.",
  },
  {
    name: "اعتماد — المنافسات المستقبلية",
    category: "خط أنابيب حكومي",
    access: "public",
    priority: "high",
    signals: ["منافسات مستقبلية", "خطط شراء", "جهات حكومية"],
    url: "https://portal.etimad.sa/ar-sa/services/servicedetails?ServiceGuid=c0274fde-bef1-4844-a65c-f2e8f1efb5ab",
    description: "خدمة رسمية لاستعراض المنافسات المستقبلية للجهات الحكومية ومتابعة الفرص قبل الطرح.",
  },
  {
    name: "المركز الوطني للتخصيص — بوابة المستثمرين",
    category: "شراكات PPP وتخصيص",
    access: "public",
    priority: "high",
    signals: ["PPP", "مشاريع مستقبلية", "EOI", "RFQ", "RFP", "قطاعات حكومية"],
    url: "https://investors.ncp.gov.sa/home",
    description: "بوابة مخصصة لفرص التخصيص والشراكة بين القطاعين العام والخاص عبر قطاعات حكومية متعددة، وتعرض خطًا مبكرًا للمشاريع قبل مرحلة التنفيذ التقليدية.",
  },
  {
    name: "المركز الوطني للتخصيص — المشاريع والفرص",
    category: "شراكات PPP وتخصيص",
    access: "public",
    priority: "high",
    signals: ["مشاريع بنية تحتية", "EOI", "مشاريع حكومية", "استثمار"],
    url: "https://www.ncp.gov.sa/",
    description: "ينشر مشاريع شراكة وتخصيص في النقل والمياه والصحة والتعليم والبلديات وغيرها، بما في ذلك دعوات إبداء الاهتمام ومراحل المشروع.",
  },
  {
    name: "الشركة السعودية لشراكات المياه — المشاريع المستقبلية",
    category: "مياه وبنية تحتية",
    access: "public",
    priority: "high",
    signals: ["IWP", "ISTP", "IWTP", "خزانات", "EOI", "RFQ", "RFP"],
    url: "https://www.swpc.sa/en/developer-qualification-initiative/",
    description: "خط مشاريع واضح لمحطات إنتاج المياه ومعالجة الصرف ومشاريع المياه المستقبلية مع برامج تأهيل المطورين ومراحل EOI/RFQ/RFP.",
  },
  {
    name: "الشركة الوطنية للمياه — علاقات الموردين",
    category: "مياه وبنية تحتية",
    access: "registration",
    priority: "high",
    signals: ["مناقصات", "ترسيات", "تأهيل مشاريع", "موردون", "مقاولون"],
    url: "https://www.nwc.com.sa/EN/BusinessSector/VendorsRelationships/Pages/default.aspx",
    description: "بوابة علاقات الموردين تشمل التسجيل وتأهيل المشاريع وإعلانات المناقصات والترسيات وإدارة الموردين والمصنعين والمقاولين.",
  },
  {
    name: "بلدي — البيانات المفتوحة",
    category: "رخص وإنشاءات وبلديات",
    access: "public",
    priority: "high",
    signals: ["رخص إنشائية", "رخص تجارية", "توزيع جغرافي", "نشاط بلدي"],
    url: "https://balady.gov.sa/ar/open-data",
    description: "بيانات مفتوحة مرخصة وقابلة لإعادة الاستخدام حول خدمات بلدي والرخص والأنشطة البلدية.",
  },
  {
    name: "وزارة البلديات والإسكان — منصة تحليل الرخص المفتوحة",
    category: "رخص وإنشاءات وبلديات",
    access: "public",
    priority: "high",
    signals: ["رخص بناء", "خرائط حرارية", "توزيع زمني", "توزيع جغرافي"],
    url: "https://baladybi.momrah.gov.sa:2030/bi/extensions/Balady_Public/Balady_Public.html",
    description: "لوحة تحليل عامة للرخص التجارية والإنشائية مع خرائط حرارية وفلاتر جغرافية وزمنية؛ مصدر مهم لرصد مناطق النشاط الإنشائي قبل ظهور المناقصات.",
  },
  {
    name: "وزارة البلديات والإسكان — البيانات المفتوحة",
    category: "رخص وإنشاءات وبلديات",
    access: "public",
    priority: "medium",
    signals: ["بلديات", "مشاريع", "خدمات", "بنية تحتية", "رخص"],
    url: "https://momah.gov.sa/en/open-data",
    description: "مجموعات بيانات بلدية وإسكانية يمكن استخدامها لبناء مؤشرات نشاط المناطق والمرافق والخدمات.",
  },
  {
    name: "الهيئة العامة للإحصاء — مؤشر تكاليف البناء",
    category: "تحليل سوق وتكاليف",
    access: "public",
    priority: "high",
    signals: ["تكلفة مواد", "أجور", "معدات", "طاقة", "تضخم بناء"],
    url: "https://www.stats.gov.sa/ar/w/cci",
    description: "مؤشر رسمي شهري لتغير تكاليف مواد البناء والعمالة وتأجير المعدات والطاقة للقطاعين السكني وغير السكني.",
  },
  {
    name: "الهيئة العامة للإحصاء — مؤشرات الأعمال قصيرة الأجل",
    category: "تحليل سوق وتكاليف",
    access: "public",
    priority: "medium",
    signals: ["رخص بناء", "نشاط إنشاء", "أجور", "مؤشرات شهرية"],
    url: "https://www.stats.gov.sa/",
    description: "تتضمن مؤشرات دورية مثل عدد رخص البناء ونشاط قطاع التشييد، ما يساعد في اكتشاف تسارع أو تباطؤ السوق حسب الفترات.",
  },
  {
    name: "البوابة الوطنية للبيانات المفتوحة",
    category: "بيانات حكومية",
    access: "public",
    priority: "high",
    signals: ["مجموعات بيانات", "CSV", "API", "جهات حكومية"],
    url: "https://open.data.gov.sa/",
    description: "المستودع الوطني المركزي لمجموعات البيانات الحكومية القابلة لإعادة الاستخدام والتحليل وربطها بمحركات البحث الداخلية.",
  },
  {
    name: "وزارة التجارة — البيانات المفتوحة",
    category: "شركات ومؤسسات",
    access: "public",
    priority: "high",
    signals: ["سجلات تجارية", "شركات", "مؤسسات", "أنشطة اقتصادية"],
    url: "https://mc.gov.sa/ar/OpenData/Pages/default.aspx",
    description: "بيانات وإحصاءات السجلات التجارية والشركات والمؤسسات ومؤشرات الأنشطة التجارية؛ مفيدة لتوسيع ملفات الشركات والموردين.",
  },
  {
    name: "المركز السعودي للأعمال",
    category: "شركات وبيئة أعمال",
    access: "public",
    priority: "medium",
    signals: ["منشآت", "تراخيص", "خدمات أعمال", "تحقق"],
    url: "https://business.sa/",
    description: "مصدر داعم لبيانات الأعمال والخدمات التنظيمية والرحلات الحكومية المرتبطة بالمنشآت.",
  },
  {
    name: "PIF Private Sector Hub — Explore Opportunities",
    category: "مشاريع كبرى وسلاسل قيمة",
    access: "public",
    priority: "high",
    signals: ["فرص استثمار", "سلاسل قيمة", "حجم استثمار", "طلب متوقع", "مشاريع كبرى"],
    url: "https://www.pif.gov.sa/en/private-sector-hub/explore-opportunities/",
    description: "فرص أعمال واستثمار وسلاسل قيمة لدى منظومة صندوق الاستثمارات العامة وشركات المحفظة مع مؤشرات للحجم الاستثماري والطلب المتوقع في بعض الفرص.",
  },
  {
    name: "PIF Contractor Program",
    category: "تأهيل المقاولين",
    access: "registration",
    priority: "high",
    signals: ["تأهيل مسبق", "خط مشاريع", "مقاولون", "تمويل"],
    url: "https://www.pif.gov.sa/en/private-sector-hub/private-sector-initiatives/contractor-program/",
    description: "تأهيل موحد للمقاولين لدى شركات التطوير التابعة للصندوق مع برامج إظهار الطلب المستقبلي والتواصل والتمويل.",
  },
  {
    name: "PIF MUSAHAMA",
    category: "موردون ومحتوى محلي",
    access: "registration",
    priority: "high",
    signals: ["موردون", "محتوى محلي", "150+ شركة محفظة", "مطابقة طلب"],
    url: "https://www.pif.gov.sa/en/private-sector-hub/private-sector-initiatives/musahama-program/musahama-platform/",
    description: "منصة موحدة لرفع ظهور الموردين المحليين وربطهم باحتياجات أكثر من 150 شركة محفظة تابعة للصندوق.",
  },
  {
    name: "مجموعة روشن — الشراكات والمقاولون والموردون",
    category: "إسكان وتطوير عقاري",
    access: "registration",
    priority: "high",
    signals: ["مقاولون", "موردون", "مطورون فرعيون", "استشاريون", "مشاريع إسكان"],
    url: "https://www.roshn.sa/ar/partnerships",
    description: "مسارات منفصلة للموردين والمقاولين والاستشاريين والمطورين الفرعيين ضمن أحد أكبر مطوري المجتمعات العمرانية في المملكة.",
  },
  {
    name: "NHC — بوابة الفرص والمنافسات",
    category: "إسكان وتطوير عقاري",
    access: "registration",
    priority: "high",
    signals: ["RFQ", "منافسات", "أوامر شراء", "تأهيل"],
    url: "https://www.nhc.sa/procurement-gate/",
    description: "تسجيل وتأهيل مزودي الخدمة واستقبال طلبات عروض الأسعار والمنافسات وأوامر الشراء.",
  },
  {
    name: "المسار الرياضي — المنافسات وعلاقات الموردين",
    category: "مشاريع كبرى وترفيه",
    access: "public",
    priority: "high",
    signals: ["منافسات عامة", "تأهيل", "موردون", "إنشاءات"],
    url: "https://sportsboulevard.sa/ar/vendors-relations",
    description: "صفحة علاقات الموردين تعرض البحث في المنافسات والتأهيل وحالات فعال/مغلق عند توفر المحتوى العام، إضافة إلى التسجيل كمورد.",
  },
  {
    name: "حديقة الملك سلمان — بوابة الموردين",
    category: "مشاريع كبرى وترفيه",
    access: "registration",
    priority: "high",
    signals: ["موردون", "مقاولون", "مشروع حضري ضخم"],
    url: "https://kingsalmanpark.sa/ar/Supplier-Portal/Supplier-portal-registration",
    description: "تسجيل الموردين المحليين والدوليين لمشروع حديقة الملك سلمان مع متطلبات تأهيل واضحة تشمل الملف المالي والفني.",
  },
  {
    name: "جدة سنترال — بوابة الموردين",
    category: "مشاريع كبرى وتطوير حضري",
    access: "registration",
    priority: "high",
    signals: ["موردون", "إنشاءات", "معالم", "تطوير حضري"],
    url: "https://www.jeddahcentral.com/suppliers",
    description: "بوابة تسجيل الموردين لمشروع جدة سنترال الذي يشمل معالم ومرافق كبرى مثل الاستاد ودار الأوبرا والمتحف والأكواريوم.",
  },
  {
    name: "رؤى المدينة — بوابة الموردين",
    category: "مشاريع كبرى وتطوير حضري",
    access: "registration",
    priority: "high",
    signals: ["موردون", "تصميم", "تطوير", "إنشاءات"],
    url: "https://www.ruaalmadinah.com/suppliers/",
    description: "بوابة شراكات وموردين لمشاريع التطوير والبنية التحتية في المدينة المنورة، وتشمل مجالات التصميم والتطوير والإنشاء.",
  },
  {
    name: "السودة للتطوير — بوابة الموردين",
    category: "سياحة وضيافة وإنشاءات",
    access: "registration",
    priority: "high",
    signals: ["موردون", "بنية تحتية", "ضيافة", "مشاريع جبلية"],
    url: "https://soudah.sa/en/soudah-development-vendors",
    description: "بوابة تسجيل وإدارة الموردين لمشاريع السودة مع تصنيفات المنتجات والخدمات ومتطلبات المحتوى المحلي.",
  },
  {
    name: "NEOM Suppliers",
    category: "مشاريع كبرى",
    access: "registration",
    priority: "high",
    signals: ["RFI", "RFQ", "RFP", "موردون", "مقاولون"],
    url: "https://www.neom.com/ar-sa/our-business/suppliers",
    description: "تسجيل الموردين والتأهل لتلقي الدعوات للمناقصات وRFP/RFQ/RFI عبر شبكة الموردين.",
  },
  {
    name: "Red Sea Global — Vendor Registration",
    category: "سياحة وضيافة وإنشاءات",
    access: "registration",
    priority: "high",
    signals: ["موردون", "مقاولون", "مشتريات مخططة", "ضيافة"],
    url: "https://redseaglobal.com/ar/vendor-registration/",
    description: "تسجيل اهتمام الموردين والمقاولين؛ المؤهلون يصلون إلى خط المشتريات المخطط والمنافسات حسب التصنيف.",
  },
  {
    name: "Qiddiya — Vendor Registration",
    category: "مشاريع كبرى وترفيه",
    access: "registration",
    priority: "high",
    signals: ["موردون", "ترفيه", "إنشاءات", "مرافق"],
    url: "https://qiddiya.com/ar/contact/vendor/",
    description: "بوابة تسجيل اهتمام الموردين للمشاركة في مشاريع وفرص القدية.",
  },
  {
    name: "New Murabba — Vendors",
    category: "تطوير حضري ومشاريع كبرى",
    access: "registration",
    priority: "high",
    signals: ["موردون", "تطوير حضري", "إنشاءات", "رياض"],
    url: "https://newmurabba.com/ar/vendors/",
    description: "شبكة الموردين للمربع الجديد وفرص المشاركة في أعمال التطوير الحضري في الرياض.",
  },
  {
    name: "الهيئة الملكية لمحافظة العلا — بوابة الموردين",
    category: "مشاريع حكومية وسياحية",
    access: "registration",
    priority: "high",
    signals: ["عطاءات", "مناقصات", "موردون", "مشاريع سياحية"],
    url: "https://www.rcu.gov.sa/business-in-alula/supplier-portal",
    description: "التسجيل شرط للمشاركة في العطاءات، والمورد المسجل يمكنه الدخول لعرض المناقصات المتاحة.",
  },
  {
    name: "أرامكو السعودية — فرص التعاقد والمقاولات",
    category: "طاقة وصناعة وصيانة",
    access: "public",
    priority: "high",
    signals: ["إنشاءات", "مشاريع رأسمالية", "صيانة", "خطوط أنابيب", "مرافق"],
    url: "https://www.aramco.com/ar/what-we-do/suppliers/contracting-opportunities",
    description: "مجالات التعاقد وقوائم العطاءات العامة والتأهيل لمشاريع البناء والصيانة والمرافق وخطوط الأنابيب والخدمات المختلفة.",
  },
  {
    name: "أرامكو السعودية — إدارة المشاريع والبناء",
    category: "طاقة وصناعة وصيانة",
    access: "public",
    priority: "high",
    signals: ["مباني", "مجمعات سكنية", "معامل", "مشاريع رأسمالية", "تأهيل"],
    url: "https://www.aramco.com/ar/what-we-do/suppliers/contracting-opportunities/project-management",
    description: "تفاصيل نطاقات فرص البناء الرأسمالية ومتطلبات التأهيل لمقاولي إدارة المشاريع والإنشاءات.",
  },
  {
    name: "الشركة السعودية للكهرباء — المقاولون والموردون",
    category: "طاقة وبنية تحتية",
    access: "registration",
    priority: "high",
    signals: ["مقاولون", "موردون", "Bidder Portal", "تأهيل مصنعين"],
    url: "https://www.se.com.sa/en/Components/Mobile/Support/FAQs/Business/Page-Components/Contractor-and-Vendor-Registration",
    description: "تسجيل المقاولين والموردين للوصول إلى بوابة مقدمي العطاءات وخدمات التأهيل والمواصفات المتاحة للمؤهلين.",
  },
  {
    name: "معادن — بوابة الموردين",
    category: "تعدين وصناعة",
    access: "registration",
    priority: "high",
    signals: ["موردون", "فرص أعمال", "معدات", "صناعة", "تعدين"],
    url: "https://www.maaden.com/supplier-portal",
    description: "بوابة تسجيل الموردين والوصول إلى فرص الأعمال لدى معادن ضمن مشاريع التعدين والمعالجة والبنية الصناعية.",
  },
  {
    name: "سابك — بوابة الموردين",
    category: "صناعة وبتروكيماويات",
    access: "registration",
    priority: "medium",
    signals: ["موردون", "معدات", "مواد", "خدمات صناعية"],
    url: "https://supplier.sabic.com/",
    description: "بوابة الموردين والعقود والمشتريات الصناعية لدى سابك، مفيدة لمسارات الخدمات والمواد والمعدات الصناعية.",
  },
  {
    name: "SAR — بوابة الموردين ومشاريع السكك الحديدية",
    category: "نقل ولوجستيات",
    access: "registration",
    priority: "high",
    signals: ["RFI", "RFQ", "RFP", "مشاريع سكك", "موردون"],
    url: "https://www.sar.com.sa/ext/vendors/",
    description: "بوابة الموردين لشركة الخطوط الحديدية السعودية مع دعم استجابات RFI/RFQ/RFP وإشارات إلى مشاريع الشركة.",
  },
  {
    name: "الهيئة العامة للطيران المدني — بوابة الموردين",
    category: "طيران ومطارات",
    access: "registration",
    priority: "medium",
    signals: ["موردون", "مطارات", "خدمات طيران", "مشاريع"],
    url: "https://gaca.gov.sa/supplier-portal",
    description: "بوابة تسجيل الموردين في قطاع الطيران ومتابعة التحديثات والمطالبات، وتفيد في بناء شبكة الموردين لقطاع المطارات والطيران.",
  },
  {
    name: "مدن — بوابة الموردين",
    category: "مدن صناعية ومشاريع",
    access: "registration",
    priority: "high",
    signals: ["مدن صناعية", "موردون", "عقود", "مصانع"],
    url: "https://modon.gov.sa/ar/Eservices/Pages/suppliers.aspx",
    description: "بوابة تسجيل وإدارة الموردين والمطالبات والتعاملات المرتبطة بعقود مدن والمشاريع الصناعية.",
  },
];

export const sourceAccessLabels: Record<SourceAccess, string> = {
  live: "متصل حيًا",
  public: "عام ومفتوح",
  registration: "يتطلب تسجيل/تأهيل",
  configured: "يتطلب إعداد رسمي",
};

export const sourcePriorityLabels: Record<SourcePriority, string> = {
  high: "أولوية قصوى",
  medium: "أولوية متوسطة",
  watch: "مراقبة",
};
