import Link from "next/link";
import { OpportunityFitBadge } from "@/components/opportunity-fit-badge";
import { currency, formatDate, statusLabel } from "@/lib/format";
import type { Tender } from "@/lib/types";

export function TenderTable({ items }: { items: Tender[] }) {
  if (!items.length) return <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><div className="text-lg font-black text-slate-800">لا توجد نتائج مطابقة</div><p className="mt-2 text-sm text-slate-500">جرّب إزالة بعض الفلاتر أو استخدام كلمات بحث أوسع.</p></div>;
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[1350px] w-full text-right text-sm"><thead className="bg-slate-50 text-xs font-extrabold text-slate-500"><tr><th className="px-4 py-4">الرقم المرجعي</th><th className="px-4 py-4">الفرصة / المنافسة</th><th className="px-4 py-4">ملاءمة بن غازي</th><th className="px-4 py-4">الجهة / المصدر</th><th className="px-4 py-4">النشاط</th><th className="px-4 py-4">المنطقة</th><th className="px-4 py-4">تاريخ النشر</th><th className="px-4 py-4">تاريخ الترسية</th><th className="px-4 py-4">قيمة الترسية</th><th className="px-4 py-4">الشركة الفائزة</th><th className="px-4 py-4">الحالة</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((tender) => <tr key={tender.id} className="align-top hover:bg-emerald-50/30"><td className="whitespace-nowrap px-4 py-4 font-bold text-slate-700">{tender.competitionNumber}</td><td className="max-w-[320px] px-4 py-4"><Link href={`/tenders/${tender.id}`} className="font-extrabold text-slate-950 hover:text-emerald-700">{tender.name}</Link></td><td className="whitespace-nowrap px-4 py-4"><OpportunityFitBadge tender={tender} /></td><td className="px-4 py-4 text-slate-600">{tender.governmentEntityName}</td><td className="px-4 py-4 text-slate-600">{tender.activityName}</td><td className="px-4 py-4 text-slate-600">{tender.regionName}</td><td className="whitespace-nowrap px-4 py-4 text-slate-600">{formatDate(tender.publicationDate)}</td><td className="whitespace-nowrap px-4 py-4 text-slate-600">{formatDate(tender.award?.awardDate)}</td><td className="whitespace-nowrap px-4 py-4 font-extrabold text-slate-900">{tender.award ? currency.format(tender.award.amount) : "—"}</td><td className="max-w-[220px] px-4 py-4">{tender.award ? <Link className="font-bold text-emerald-800 hover:underline" href={`/companies/${tender.award.companySlug}`}>{tender.award.companyName}</Link> : "—"}</td><td className="whitespace-nowrap px-4 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-extrabold ${tender.status === "awarded" ? "bg-emerald-100 text-emerald-800" : tender.status === "open" ? "bg-blue-100 text-blue-800" : tender.status === "cancelled" ? "bg-rose-100 text-rose-800" : "bg-slate-100 text-slate-700"}`}>{statusLabel(tender.status)}</span></td></tr>)}</tbody></table></div></div>;
}
