"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { TenderTable } from "@/components/tender-table";
import type { Activity, GovernmentEntity, PaginatedTenders, Region, TenderFilters } from "@/lib/types";

interface FilterOptions { governmentEntities: GovernmentEntity[]; activities: Activity[]; regions: Region[]; sectors: string[]; }
interface Props { initialData: PaginatedTenders; options: FilterOptions; initialFilters: TenderFilters; }
function toParams(filters: TenderFilters) { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== "") params.set(key, String(value)); }); return params; }

export function TenderExplorer({ initialData, options, initialFilters }: Props) {
  const [filters, setFilters] = useState<TenderFilters>({ ...initialFilters, page: initialFilters.page ?? 1, pageSize: initialFilters.pageSize ?? 10 });
  const [data, setData] = useState(initialData); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const firstRender = useRef(true);
  const fetchData = useCallback(async (nextFilters: TenderFilters) => { setLoading(true); setError(""); try { const params = toParams(nextFilters); const response = await fetch(`/api/tenders?${params.toString()}`, { cache: "no-store" }); if (!response.ok) throw new Error("فشل تحميل النتائج"); const payload = (await response.json()) as PaginatedTenders; setData(payload); const publicParams = new URLSearchParams(params); if (nextFilters.awarded) publicParams.set("awarded", "yes"); window.history.replaceState(null, "", `${window.location.pathname}?${publicParams.toString()}`); } catch (err) { setError(err instanceof Error ? err.message : "حدث خطأ غير متوقع"); } finally { setLoading(false); } }, []);
  useEffect(() => { if (firstRender.current) { firstRender.current = false; return; } const timer = window.setTimeout(() => void fetchData(filters), filters.q !== undefined ? 350 : 0); return () => window.clearTimeout(timer); }, [filters, fetchData]);
  const set = (key: keyof TenderFilters, value: string | number | boolean | undefined) => setFilters((current) => ({ ...current, [key]: value === "" ? undefined : value, page: 1 }));
  const hasFilters = useMemo(() => Object.entries(filters).some(([key, value]) => !["page", "pageSize", "sort", "order"].includes(key) && value !== undefined && value !== ""), [filters]);
  return <section className="space-y-4">
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative flex-1"><input value={filters.q ?? ""} onChange={(event) => set("q", event.target.value)} placeholder="ابحث برقم المنافسة، الاسم، الجهة أو الشركة الفائزة..." className="h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-sm font-semibold outline-none ring-emerald-200 transition focus:border-emerald-600 focus:ring-4" />{loading && <span className="absolute left-4 top-3.5 text-xs font-bold text-emerald-700">جارٍ التحديث...</span>}</div><label className="flex h-12 cursor-pointer items-center justify-between gap-4 rounded-xl border border-slate-200 px-4 font-bold text-slate-700 lg:min-w-44"><span>الترسيات فقط</span><input type="checkbox" checked={Boolean(filters.awarded)} onChange={(event) => set("awarded", event.target.checked || undefined)} className="h-5 w-5 accent-emerald-700" /></label></div>
      <details className="mt-4 group" open={hasFilters && !filters.q && !filters.awarded}><summary className="cursor-pointer list-none text-sm font-black text-emerald-800">الفلاتر المتقدمة <span className="mr-1 text-slate-400 group-open:hidden">+</span></summary><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        <Select label="الجهة الحكومية" value={filters.governmentEntity} onChange={(v) => set("governmentEntity", v)} options={options.governmentEntities.map((x) => [x.id, x.name])} /><Select label="النشاط" value={filters.activity} onChange={(v) => set("activity", v)} options={options.activities.map((x) => [x.id, x.name])} /><Select label="المجال" value={filters.sector} onChange={(v) => set("sector", v)} options={options.sectors.map((x) => [x, x])} /><Select label="المنطقة" value={filters.region} onChange={(v) => set("region", v)} options={options.regions.map((x) => [x.id, x.name])} />
        <Input label="تاريخ النشر من" type="date" value={filters.publicationFrom} onChange={(v) => set("publicationFrom", v)} /><Input label="تاريخ النشر إلى" type="date" value={filters.publicationTo} onChange={(v) => set("publicationTo", v)} /><Input label="تاريخ الترسية من" type="date" value={filters.awardFrom} onChange={(v) => set("awardFrom", v)} /><Input label="تاريخ الترسية إلى" type="date" value={filters.awardTo} onChange={(v) => set("awardTo", v)} />
        <Input label="القيمة التقديرية من" type="number" value={filters.estimatedMin} onChange={(v) => set("estimatedMin", v ? Number(v) : undefined)} /><Input label="القيمة التقديرية إلى" type="number" value={filters.estimatedMax} onChange={(v) => set("estimatedMax", v ? Number(v) : undefined)} /><Input label="قيمة الترسية من" type="number" value={filters.awardMin} onChange={(v) => set("awardMin", v ? Number(v) : undefined)} /><Input label="قيمة الترسية إلى" type="number" value={filters.awardMax} onChange={(v) => set("awardMax", v ? Number(v) : undefined)} />
        <Select label="حالة المنافسة" value={filters.status} onChange={(v) => set("status", v)} options={[["open", "مفتوحة"], ["closed", "مغلقة"], ["awarded", "تمت الترسية"], ["cancelled", "ملغاة"]]} /><Select label="حالة الترسية" value={filters.awarded === undefined ? "" : String(filters.awarded)} onChange={(v) => set("awarded", v === "" ? undefined : v === "true")} options={[["true", "تمت الترسية"], ["false", "لم تتم الترسية"]]} /><Input label="المورد الفائز" value={filters.winner} onChange={(v) => set("winner", v)} /><Select label="الترتيب" value={`${filters.sort ?? "publicationDate"}:${filters.order ?? "desc"}`} onChange={(v) => { const [sort, order] = v.split(":"); setFilters((current) => ({ ...current, sort: sort as TenderFilters["sort"], order: order as TenderFilters["order"], page: 1 })); }} options={[["publicationDate:desc", "الأحدث نشرًا"], ["awardDate:desc", "الأحدث ترسية"], ["awardAmount:desc", "أعلى قيمة ترسية"], ["estimatedValue:desc", "أعلى قيمة تقديرية"], ["name:asc", "الاسم أبجديًا"]]} />
      </div><div className="mt-4 flex justify-end"><button type="button" onClick={() => setFilters({ page: 1, pageSize: 10, sort: "publicationDate", order: "desc" })} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-50">مسح الفلاتر</button></div></details>
    </div>
    <div className="flex items-center justify-between text-sm text-slate-500"><span>تم العثور على <strong className="text-slate-900">{data.total}</strong> نتيجة</span><select value={filters.pageSize ?? 10} onChange={(e) => set("pageSize", Number(e.target.value))} className="rounded-lg border border-slate-200 bg-white px-3 py-2 font-bold"><option value="10">10 / صفحة</option><option value="25">25 / صفحة</option><option value="50">50 / صفحة</option></select></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}<div className={loading ? "opacity-60 transition" : "transition"}><TenderTable items={data.items} /></div>
    <div className="flex items-center justify-center gap-3"><button disabled={data.page <= 1 || loading} onClick={() => setFilters((current) => ({ ...current, page: Math.max(1, (current.page ?? 1) - 1) }))} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40">السابق</button><span className="text-sm font-bold text-slate-600">صفحة {data.page} من {data.totalPages}</span><button disabled={data.page >= data.totalPages || loading} onClick={() => setFilters((current) => ({ ...current, page: Math.min(data.totalPages, (current.page ?? 1) + 1) }))} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40">التالي</button></div>
  </section>;
}
function Select({ label, value, onChange, options }: { label: string; value?: string; onChange: (value: string) => void; options: string[][] }) { return <label className="space-y-1.5 text-xs font-extrabold text-slate-600"><span>{label}</span><select value={value ?? ""} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-800 outline-none focus:border-emerald-600"><option value="">الكل</option>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>; }
function Input({ label, type = "text", value, onChange }: { label: string; type?: string; value?: string | number; onChange: (value: string) => void }) { return <label className="space-y-1.5 text-xs font-extrabold text-slate-600"><span>{label}</span><input type={type} min={type === "number" ? 0 : undefined} value={value ?? ""} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-800 outline-none focus:border-emerald-600" /></label>; }
